FoodMenu/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FoodMenu.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FoodMenu.Controllers
{
    public class FoodController : Controller
    {
        private DataContext _context;
        public FoodController(DataContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(_context.Foods);
        }

        public IActionResult Create()
        {
            return View("FoodEditor");
        }

        public IActionResult Edit(int id)
        {
            return View("FoodEditor",
                _context
                    .Foods
                    .FirstOrDefault(i => i.FoodId == id));
        }

        [HttpPost]
        public IActionResult Edit(Food entity)
        {
            if (entity.FoodId == 0)
            {
                _context.Foods.Add(entity);
            }
            else
            {
                _context.Foods.Update(entity);
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        //[HttpPost]
        public IActionResult Delete(int id)
        {
            var entity = _context.Foods.FirstOrDefault(i => i.FoodId == id);
            _context.Foods.Remove(entity);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

FoodMenu/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FoodMenu.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FoodMenu.Controllers
{
    public class MenuController : Controller
    {
        private DataContext _context;
        public MenuController(DataContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = _context
                .Menus
                .Include(i => i.FoodMenus)
                .ThenInclude(i => i.Food)
                .ToList();

            return View(model);
        }

        public IActionResult Create()
        {
            return View("MenuDateEditor");
        }

        public IActionResult Edit(int id)
        {
            return View("MenuDateEditor",
                _context
                    .Menus
                    .FirstOrDefault(i => i.MenuId == id));
        }

        [HttpPost]
        public IActionResult Edit(Menu entity)
        {
            if (entity.MenuId == 0)
            {
                _context.Menus.Add(entity);
            }
            else
            {
                _context.Menus.Update(entity);
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        //[HttpPost]
        public IActionResult Delete(int id)
        {
            var entity = _context.Menus.FirstOrDefault(i => i.MenuId == id);
            _context.Menus.Remove(entity);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult EditMenu(int id)
        {
            ViewBag.Foods = _context.Foods.Include(p => p.FoodMenus);
            return View("MenuEditor", _context.Menus.Find(id));
        }
        [HttpPost]
        public IActionResult EditMenu(int id, int[] foodid)
        {
            Menu menu = _context
                .Menus
                .Include(s => s.FoodMenus)
                .First(s => s.MenuId == id);

            menu.FoodMenus = foodid.Select(pid
                => new Models.FoodMenu
                {
                    MenuId = id,
                    FoodId = pid
                }).ToList();
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FoodMenu/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FoodMenu.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FoodMenu.Controllers
{
    public class UserController : Controller
    {
        private DataContext _context;
        public UserController(DataContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(_context.Users);
        }

        public IActionResult Create()
        {
            return View("UserEditor");
        }

        public IActionResult Edit(int id)
        {
            return View("UserEditor",
                _context
                    .Users
                    .FirstOrDefault(i => i.UserId == id));
        }

        [HttpPost]
        public IActionResult Edit(User entity)
        {
            if (entity.UserId == 0)
            {
                _context.Users.Add(entity);
            }
            else
            {
                _context.Users.Update(entity);
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        //[HttpPost]
        public IActionResult Delete(int id)
        {
            var entity = _context.Users.FirstOrDefault(i => i.UserId == id);
            _context.Users.Remove(entity);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

FoodMenu/Controllers/UserMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FoodMenu.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FoodMenu.Controllers
{
    public class UserMenuController : Controller
    {
        private DataContext _context;
        public UserMenuController(DataContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = _context
                .Menus
                .Include(i => i.UserMenus)
                .ThenInclude(i => i.User)
                .ToList();

            return View(model);
        }

        public IActionResult EditMenu(int id)
        {
            ViewBag.Users = _context.Users.Include(p => p.UserMenus);
            return View("UserMenuEditor", _context.Menus.Find(id));
        }
        [HttpPost]
        public IActionResult EditMenu(int id, int[] userid)
        {
            Menu menu = _context
                .Menus
                .Include(s => s.UserMenus)
                .First(s => s.MenuId == id);

            menu.UserMenus = userid.Select(pid
                => new UserMenu
                {
                    MenuId = id,
                    UserId = pid
                }).ToList();
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FoodMenu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/vendor/jquery/dist/jquery.min.js"></script>
    <link href="~/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Yemek</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Liste<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Food" asp-action="Index">Yemek</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Menu" asp-action="Index">Menü</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="User" asp-action="Index">Kullanıcı</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="UserMenu" asp-action="Index">Katılımcı</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
    <script src="~/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>